security:
  username: user
  password: passwd123@

services:
  weather:
    uri: http://api.openweathermap.org/data/2.5/weather
    id: 398b8ddf855a1fb8322da99648fb4ebc
    timeout: 5000
  spotify:
    token:
      uri: https://accounts.spotify.com
      path: /api/token
      id: c724fa1199704f74b0f2b46b62408e2e
      secret: 17d962e5a2304d8383cfcbb84cc9e135
    uri: https://api.spotify.com
    timeout: 5000

feign:
  client:
    config:
      feignName:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
        decode404: false

logging:
  level: DEBUG